name: Develop Groups 10 to Auto-Develop Branch

on:
  push:
    branches:
      - develop-G10

jobs:
  update:
    name: "Auto Merge Groups Develop 10 to auto-develop branch"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸšš - Checkout develop"
        uses: actions/checkout@v2

      - name: "ðŸ”€ - Merge develop-G10 to auto-develop"
        uses: mtanzi/action-automerge@v1
        id: mergeG1
        with:
          github_token: ${{ github.token }}
          source: 'develop-G10'
          target: 'auto-develop'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
